### ISSUE TITLE
Basic map information

### ISSUE THREAD

**Issue by dertseha** [inkyblackness/ss-specs#4]
Get some initial map (layout) information ported from old specs and expand on new information.

**Comment by dertseha** [comment]
I now removed the map dimension (width/horizontal height) info. Since the engine does not respect these values, there is no point in keeping them.

Furthermore I updated the vertical height information. With explicit values, the height becomes easier to understand.

**Comment by dertseha** [comment]
I found some flags that haven't been documented or explained yet.
`0x00000040` and `0x00000020` are set for the tiles at the second Diego confrontation; Second also set for one arbitrary tile on first level.
`0x00000080` has been found in a closed-off tile on alpha grove - nothing special about that tile.

**Comment by dertseha** [comment]
Thinking about it, perhaps this `0x00000040` means "don't resurrect" - Since at Diego's second confrontation, it wouldn't be possible to resurrect - Try this out some time.

**Comment by jramstedt** [comment]
`0x00000020` is Texture flip

`0x00000040` is Alternate texture flip
North and South wall textures (Y axis) and West and East wall textures (X axis) are flipped in alternating matter depending on tile X and Y positions.

Textures are flipped horizontally.

`0x00000040` Alternate flipping is calculated like this:
flipX = ((tileX & 1) == 1) ^ ((tileY & 1) == 0)
flipY = !flipX

`0x00000020` flips both axis:
flipX = !flipX
flipY = !flipY

These need to be handled in that order.
`0x00000040` first and then `0x00000020`

I have these working in my SSImporter repository.

**Comment by dertseha** [comment]
Thank you for your contribution! I was wondering what governs the flipping and now it's clear why level 9 is flooded with these two flags.

**Comment by dertseha** [comment]
New revelation: the engine doesn't properly support any level as cyberspace level. Only 10, 14 and 15 work. This came out of non-working items (#39) in cyberspace, including exit ports crashing the game.

**Comment by dertseha** [comment]
Going over all the map-initialization routines, it seems like maps were "meant" to support any sizes, yet due to the hardcoded initialization of a static map, the maximum size is limited to 4096 tiles (statics.h).
Thanks to all that macro-trickery for accessing single tiles, I believe it may be possible to make smaller maps (as long as a side-length is a multiple of two, to satisfy the shift fields), yet there's hardly a point to that. There was no memory concern back then, and hardly is nowadays.

**Comment by dertseha** [comment]
Level and map information updated as per source. No big revelations here, only clarifications and certainty for the existing stuff.
There's still one unknown tile field that appears to be used, yet only somehow arcane in the renderer; Given that its neighbors are not used, I suppose it's another leftover. Can be handled in a separate issue if needed.
And closed.
